services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/work:cached
      - ../frontend:/app
      - web_node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    tty: true
    init: true

volumes:
  web_node_modules: